<a href="https://colab.research.google.com/github/haleemaraza/numpy/blob/main/numpy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A= np.array([1,2,3,4])

In [ ]:
A.dtype

dtype('int64')

In [ ]:
A[1:3]

array([2, 3])

In [ ]:
A[0:]

array([1, 2, 3, 4])

In [ ]:
A[2:-1]

array([3])

In [ ]:
A[::2]

array([1, 3])

In [ ]:
A[::3]

array([1, 4])

In [ ]:
A[1],A[2],A[3]

(np.int64(2), np.int64(3), [3])

In [ ]:
A[[1,2,-1]]

array([2, 3, 4])

In [ ]:
d=np.array([1,2,3], dtype=float)
d.dtype
print(d)

[1. 2. 3.]


In [ ]:
B=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
B.shape

(3, 3)

In [ ]:
B.size

9

In [ ]:
B.ndim

2

In [ ]:
C=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [0,1,2]
    ]
])

In [ ]:
C.shape

(2, 2, 3)

In [ ]:
C.size

12

In [ ]:
C.ndim

3

In [ ]:
D=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
D.dtype

dtype('int64')

In [ ]:
D[0][2]

np.int64(3)

In [ ]:
D[0:1,0:1]

array([[1]])

In [ ]:
D[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
D[0]=np.array([10,10,10])

In [ ]:
D

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
D

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
D[0]=22

In [ ]:
D

array([[22, 22, 22],
       [10, 10, 10],
       [10, 10, 10]])

In [ ]:
E=np.arange(80).reshape(5,4,4)

In [ ]:
E

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]],

       [[64, 65, 66, 67],
        [68, 69, 70, 71],
        [72, 73, 74, 75],
        [76, 77, 78, 79]]])

In [ ]:
E[2:3,:3,0]

In [ ]:
E[2:3,:3,0].shape

(1, 3)

In [ ]:
E[3:4,2:4,1:4]

array([[[57, 58, 59],
        [61, 62, 63]]])

In [ ]:
np.zeros(12).reshape(3,2,2)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
np.ones((5,5))*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

# **Summary** **staistic**

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
a.mean()

np.float64(3.0)

In [ ]:
a.sum()

np.int64(15)

In [ ]:
a.std()

np.float64(1.4142135623730951)

In [ ]:
a.var()

np.float64(2.0)

In [ ]:
F =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [ ]:
F.mean()

np.float64(5.0)

In [ ]:
F.sum()

np.int64(45)

In [ ]:
F.std()

np.float64(2.581988897471611)

In [ ]:
A.sum(axis=0)

np.int64(10)

In [ ]:
A.mean(axis=0)

np.float64(2.5)

# Broadcasting and Vectorized operations

In [86]:
a= np.arange(4)

In [87]:
a

array([0, 1, 2, 3])

In [88]:
a+10

array([10, 11, 12, 13])

In [89]:
a+=100

In [90]:
a

array([100, 101, 102, 103])

In [93]:
l=[1,2,3,4,5]

In [94]:
[i*10 for i in l]

[10, 20, 30, 40, 50]

# Boolean array

In [119]:
a=np.arange(5)

In [97]:
a

array([0, 1, 2, 3])

In [98]:
a[0],a[-1]

(np.int64(0), np.int64(3))

In [99]:
a[[0,-1]]

array([0, 3])

In [100]:
a[[True,False,True,False]]

array([0, 2])

In [106]:
a[True,False,True,False]

array([], shape=(0, 4), dtype=int64)

In [101]:
a>=2

array([False, False,  True,  True])

In [103]:
a>2

array([False, False, False,  True])

In [104]:
a[a>=2]

array([2, 3])

In [107]:
a.mean()

np.float64(1.5)

In [109]:
a[a>a.mean()]

array([2, 3])

In [110]:
a[~(a>a.mean())]

array([0, 1])

In [111]:
a[(a==0)|(a==1)]

array([0, 1])

In [120]:
a[(a<=2) & (a%2==0)]

array([0, 2])

In [142]:
A = np.random.randint(0,100, size=(3,3))

In [138]:
A

array([[26, 63, 95],
       [52, 36, 33],
       [31, 32, 87]])

In [143]:
A>30

array([[False,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

In [144]:
A[A>31]

array([37, 41, 96, 78, 40])

# Linear Algebra

In [145]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [152]:
B=np.array([
    [6,5,1],
    [7,8,2],
    [9,3,1]
])

In [155]:
A.dot(B) # A's row on index 0 will multiply by B's column on index 0

array([[ 47,  30,   8],
       [113,  78,  20],
       [179, 126,  32]])

In [154]:
B.T # turning B's row into column

array([[6, 7, 9],
       [5, 8, 3],
       [1, 2, 1]])

In [156]:
A@B

array([[ 47,  30,   8],
       [113,  78,  20],
       [179, 126,  32]])

In [157]:
B.T @A

array([[ 97, 119, 141],
       [ 58,  74,  90],
       [ 16,  20,  24]])

In [151]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **size** **of** **object** **in** **memory**

# Int, float

In [159]:
import sys
#An int in python is  > 24 bytes
sys.getsizeof(1)

28

In [160]:
#longa are even larger
sys.getsizeof(10**100)

72

In [161]:
#numpy size is much smaller
np.dtype(int).itemsize

8

In [164]:
np.dtype(float).itemsize

8

# Lists are even larger

In [165]:
# A one-element list
sys.getsizeof([1])

64

In [166]:
#an array of one element in numpy
np.array([1]).nbytes

8

# And performance is also important

In [167]:
l=list(range(100000))

In [169]:
a=np.array(100000)

In [170]:
%time np.sum(a**2)

CPU times: user 566 µs, sys: 0 ns, total: 566 µs
Wall time: 575 µs


np.int64(10000000000)

In [173]:
%time sum([x**2 for x in l])

CPU times: user 7.52 ms, sys: 6.19 ms, total: 13.7 ms
Wall time: 27.8 ms


333328333350000

IMP numpy function

In [174]:
#Random

In [175]:
np.random.random(size=2)

array([0.24873401, 0.41517313])

In [182]:
np.random.normal(size=2)

array([-2.20891043,  1.63075748])

In [178]:
np.random.rand(2,4)

array([[0.00174897, 0.16348232, 0.42246959, 0.10375206],
       [0.85583577, 0.93280243, 0.39212469, 0.05764748]])

In [183]:
#arrange

In [185]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [186]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [190]:
np.arange(0,8,.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. , 6.3, 6.6, 6.9, 7.2, 7.5,
       7.8])

In [193]:
#reshape

In [194]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [195]:
#Linspace

In [197]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [200]:
np.linspace(0,1,20,False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [201]:
#empty

In [202]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [203]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [204]:
#identity and eye

In [205]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [206]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [210]:
np.eye(8,4,k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [211]:
"hello world" [6]

'w'

In [212]:
print(np.__version__)

2.1.3
